In [69]:
import numpy as np
import pandas as pd

In [70]:
dict1 = {
    "name" : ["larry", "rohan", "nilay", "shubh"],
    "marks" : [92,54, 66, 44],
    "city" : ["rampur", "bilaspur", "angul", "chennai"]

}

In [71]:
df = pd.DataFrame(dict1)

In [72]:
df

    name  marks      city
0  larry     92    rampur
1  rohan     54  bilaspur
2  nilay     66     angul
3  shubh     44   chennai

In [73]:
df.to_csv('friends.csv')

In [74]:
df.to_csv('friends.csv', index=False)

In [75]:
df.head(3)

    name  marks      city
0  larry     92    rampur
1  rohan     54  bilaspur
2  nilay     66     angul

In [76]:
df.describe()

          marks
count   4.00000
mean   64.00000
std    20.72036
min    44.00000
25%    51.50000
50%    60.00000
75%    72.50000
max    92.00000

In [77]:
new_csv = pd.read_csv('new.csv')

In [78]:
new_csv

   Train No  Speed      City
0     12621     92    rampur
1     12624    120  bilaspur
2     15426     88     angul
3     17480     67   chennai

In [79]:
new_csv['Speed'][0]

np.int64(92)

In [80]:
new_csv.loc[0, 'Speed'] = 80 # new_csv['Speed'][0] = 80

In [81]:
new_csv

   Train No  Speed      City
0     12621     80    rampur
1     12624    120  bilaspur
2     15426     88     angul
3     17480     67   chennai

In [82]:
new_csv.index = ['first', 'second', 'third','fourth']

In [83]:
new_csv

        Train No  Speed      City
first      12621     80    rampur
second     12624    120  bilaspur
third      15426     88     angul
fourth     17480     67   chennai

In [84]:
ser = pd.Series(np.random.rand(20))

In [85]:
type(ser)

pandas.Series

In [86]:
newdf = pd.DataFrame(np.random.rand(250,6), index = np.arange(250))

In [87]:
type(newdf)

pandas.DataFrame

In [88]:
newdf.head()

          0         1         2         3         4         5
0  0.311486  0.973499  0.255598  0.240987  0.554703  0.713108
1  0.774588  0.528126  0.611762  0.452708  0.491249  0.024446
2  0.422670  0.687773  0.020417  0.961904  0.652673  0.951502
3  0.738643  0.545129  0.073017  0.687705  0.409687  0.003974
4  0.642763  0.627944  0.355112  0.092956  0.376108  0.236844

In [89]:
newdf.describe()

                0           1           2           3           4           5
count  250.000000  250.000000  250.000000  250.000000  250.000000  250.000000
mean     0.519155    0.502291    0.502294    0.499244    0.469387    0.515365
std      0.281196    0.286282    0.286385    0.294326    0.279475    0.288529
min      0.006307    0.002045    0.001501    0.003304    0.000359    0.003974
25%      0.274339    0.236403    0.265444    0.242861    0.242498    0.297733
50%      0.556772    0.532043    0.523416    0.460099    0.453749    0.514579
75%      0.758139    0.736122    0.739256    0.749449    0.681268    0.759999
max      0.998267    0.998753    0.999734    0.996651    0.995287    0.999464

In [90]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
5    float64
dtype: object

In [91]:
newdf

            0         1         2         3         4         5
0    0.311486  0.973499  0.255598  0.240987  0.554703  0.713108
1    0.774588  0.528126  0.611762  0.452708  0.491249  0.024446
2    0.422670  0.687773  0.020417  0.961904  0.652673  0.951502
3    0.738643  0.545129  0.073017  0.687705  0.409687  0.003974
4    0.642763  0.627944  0.355112  0.092956  0.376108  0.236844
..        ...       ...       ...       ...       ...       ...
245  0.265855  0.527188  0.214017  0.861031  0.360308  0.656181
246  0.718948  0.143396  0.757879  0.240438  0.853661  0.078308
247  0.007139  0.864171  0.592912  0.450697  0.363164  0.985682
248  0.008315  0.801107  0.624795  0.420353  0.123617  0.630029
249  0.594690  0.750063  0.771846  0.872772  0.832436  0.971130

[250 rows x 6 columns]

In [92]:
newdf.loc[0,0] = 0.334

In [93]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       240, 241, 242, 243, 244, 245, 246, 247, 248, 249],
      dtype='int64', length=250)

In [94]:
newdf.columns

RangeIndex(start=0, stop=6, step=1)

In [95]:
newdf[0] = newdf[0].astype("float64")

In [96]:
newdf.to_numpy()

array([[0.334     , 0.97349851, 0.25559833, 0.24098697, 0.55470341,
        0.71310752],
       [0.77458821, 0.52812567, 0.61176169, 0.45270827, 0.49124853,
        0.02444616],
       [0.42267017, 0.68777268, 0.02041673, 0.96190421, 0.65267252,
        0.95150237],
       ...,
       [0.00713881, 0.86417148, 0.59291212, 0.45069683, 0.36316374,
        0.98568199],
       [0.00831518, 0.80110733, 0.6247951 , 0.42035306, 0.12361733,
        0.63002909],
       [0.59469025, 0.75006254, 0.77184583, 0.87277185, 0.83243573,
        0.97112998]], shape=(250, 6))

In [97]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,240,241,242,243,244,245,246,247,248,249
0,0.334000,0.774588,0.422670,0.738643,0.642763,0.341773,0.150943,0.610974,0.694679,0.556096,...,0.670374,0.718048,0.476831,0.943759,0.939621,0.265855,0.718948,0.007139,0.008315,0.594690
1,0.973499,0.528126,0.687773,0.545129,0.627944,0.834999,0.885933,0.155576,0.204237,0.677447,...,0.023582,0.007675,0.007774,0.127224,0.702315,0.527188,0.143396,0.864171,0.801107,0.750063
2,0.255598,0.611762,0.020417,0.073017,0.355112,0.991950,0.445504,0.822364,0.638010,0.811642,...,0.686594,0.477319,0.570547,0.644457,0.357984,0.214017,0.757879,0.592912,0.624795,0.771846
3,0.240987,0.452708,0.961904,0.687705,0.092956,0.213535,0.070123,0.314022,0.178580,0.647080,...,0.543084,0.827560,0.935611,0.690111,0.145913,0.861031,0.240438,0.450697,0.420353,0.872772
4,0.554703,0.491249,0.652673,0.409687,0.376108,0.595579,0.194227,0.384049,0.787157,0.135909,...,0.002648,0.709548,0.851749,0.310961,0.908306,0.360308,0.853661,0.363164,0.123617,0.832436
5,0.713108,0.024446,0.951502,0.003974,0.236844,0.871555,0.051800,0.309811,0.998506,0.420859,...,0.742594,0.894977,0.634749,0.515992,0.668198,0.656181,0.078308,0.985682,0.630029,0.971130

In [98]:
newdf.sort_index(axis = 0, ascending = False)

            0         1         2         3         4         5
249  0.594690  0.750063  0.771846  0.872772  0.832436  0.971130
248  0.008315  0.801107  0.624795  0.420353  0.123617  0.630029
247  0.007139  0.864171  0.592912  0.450697  0.363164  0.985682
246  0.718948  0.143396  0.757879  0.240438  0.853661  0.078308
245  0.265855  0.527188  0.214017  0.861031  0.360308  0.656181
..        ...       ...       ...       ...       ...       ...
4    0.642763  0.627944  0.355112  0.092956  0.376108  0.236844
3    0.738643  0.545129  0.073017  0.687705  0.409687  0.003974
2    0.422670  0.687773  0.020417  0.961904  0.652673  0.951502
1    0.774588  0.528126  0.611762  0.452708  0.491249  0.024446
0    0.334000  0.973499  0.255598  0.240987  0.554703  0.713108

[250 rows x 6 columns]

In [99]:
newdf.sort_index(axis = 1, ascending = False)

            5         4         3         2         1         0
0    0.713108  0.554703  0.240987  0.255598  0.973499  0.334000
1    0.024446  0.491249  0.452708  0.611762  0.528126  0.774588
2    0.951502  0.652673  0.961904  0.020417  0.687773  0.422670
3    0.003974  0.409687  0.687705  0.073017  0.545129  0.738643
4    0.236844  0.376108  0.092956  0.355112  0.627944  0.642763
..        ...       ...       ...       ...       ...       ...
245  0.656181  0.360308  0.861031  0.214017  0.527188  0.265855
246  0.078308  0.853661  0.240438  0.757879  0.143396  0.718948
247  0.985682  0.363164  0.450697  0.592912  0.864171  0.007139
248  0.630029  0.123617  0.420353  0.624795  0.801107  0.008315
249  0.971130  0.832436  0.872772  0.771846  0.750063  0.594690

[250 rows x 6 columns]

In [100]:
newdf.head()

          0         1         2         3         4         5
0  0.334000  0.973499  0.255598  0.240987  0.554703  0.713108
1  0.774588  0.528126  0.611762  0.452708  0.491249  0.024446
2  0.422670  0.687773  0.020417  0.961904  0.652673  0.951502
3  0.738643  0.545129  0.073017  0.687705  0.409687  0.003974
4  0.642763  0.627944  0.355112  0.092956  0.376108  0.236844

### newdf2 is a view of newdf, so it changes newdf also

In [101]:
newdf2 = newdf

In [102]:
newdf2.loc[0,0] = 1212

In [104]:
newdf

               0         1         2         3         4         5
0    1212.000000  0.973499  0.255598  0.240987  0.554703  0.713108
1       0.774588  0.528126  0.611762  0.452708  0.491249  0.024446
2       0.422670  0.687773  0.020417  0.961904  0.652673  0.951502
3       0.738643  0.545129  0.073017  0.687705  0.409687  0.003974
4       0.642763  0.627944  0.355112  0.092956  0.376108  0.236844
..           ...       ...       ...       ...       ...       ...
245     0.265855  0.527188  0.214017  0.861031  0.360308  0.656181
246     0.718948  0.143396  0.757879  0.240438  0.853661  0.078308
247     0.007139  0.864171  0.592912  0.450697  0.363164  0.985682
248     0.008315  0.801107  0.624795  0.420353  0.123617  0.630029
249     0.594690  0.750063  0.771846  0.872772  0.832436  0.971130

[250 rows x 6 columns]

In [106]:
newdf2 = newdf.copy()

In [107]:
newdf2.loc[0,0] = 3344

In [108]:
newdf2.head()

             0         1         2         3         4         5
0  3344.000000  0.973499  0.255598  0.240987  0.554703  0.713108
1     0.774588  0.528126  0.611762  0.452708  0.491249  0.024446
2     0.422670  0.687773  0.020417  0.961904  0.652673  0.951502
3     0.738643  0.545129  0.073017  0.687705  0.409687  0.003974
4     0.642763  0.627944  0.355112  0.092956  0.376108  0.236844

In [110]:
newdf.head()

             0         1         2         3         4         5
0  1212.000000  0.973499  0.255598  0.240987  0.554703  0.713108
1     0.774588  0.528126  0.611762  0.452708  0.491249  0.024446
2     0.422670  0.687773  0.020417  0.961904  0.652673  0.951502
3     0.738643  0.545129  0.073017  0.687705  0.409687  0.003974
4     0.642763  0.627944  0.355112  0.092956  0.376108  0.236844

In [111]:
newdf.loc[0,0] = 12314

In [112]:
newdf.head(2)

              0         1         2         3         4         5
0  12314.000000  0.973499  0.255598  0.240987  0.554703  0.713108
1      0.774588  0.528126  0.611762  0.452708  0.491249  0.024446

In [113]:
newdf.columns = list("ABCDEF")

In [114]:
newdf.head(2)

              A         B         C         D         E         F
0  12314.000000  0.973499  0.255598  0.240987  0.554703  0.713108
1      0.774588  0.528126  0.611762  0.452708  0.491249  0.024446

In [115]:
newdf.loc[0,0] = 124124

In [117]:
newdf.head(2)

              A         B         C         D         E         F         0
0  12314.000000  0.973499  0.255598  0.240987  0.554703  0.713108  124124.0
1      0.774588  0.528126  0.611762  0.452708  0.491249  0.024446       NaN

In [118]:
newdf.loc[0,'A'] = 1274575

In [119]:
newdf.head(2)

              A         B         C         D         E         F         0
0  1.274575e+06  0.973499  0.255598  0.240987  0.554703  0.713108  124124.0
1  7.745882e-01  0.528126  0.611762  0.452708  0.491249  0.024446       NaN

row axis = 0, column axis = 1

In [121]:
newdf = newdf.drop(0,axis=1) #axis = 0 drops row

In [122]:
newdf.head(2)

              A         B         C         D         E         F
0  1.274575e+06  0.973499  0.255598  0.240987  0.554703  0.713108
1  7.745882e-01  0.528126  0.611762  0.452708  0.491249  0.024446

In [125]:
newdf.loc[[1,2],["C","D"]]

          C         D
1  0.611762  0.452708
2  0.020417  0.961904

In [126]:
newdf.loc[[1,2],:]

          A         B         C         D         E         F
1  0.774588  0.528126  0.611762  0.452708  0.491249  0.024446
2  0.422670  0.687773  0.020417  0.961904  0.652673  0.951502

In [127]:
newdf.loc[:,["C","D"]]

            C         D
0    0.255598  0.240987
1    0.611762  0.452708
2    0.020417  0.961904
3    0.073017  0.687705
4    0.355112  0.092956
..        ...       ...
245  0.214017  0.861031
246  0.757879  0.240438
247  0.592912  0.450697
248  0.624795  0.420353
249  0.771846  0.872772

[250 rows x 2 columns]

In [129]:
newdf.loc[(newdf["A"]<0.3) & (newdf["C"]>0.1)]

            A         B         C         D         E         F
6    0.150943  0.885933  0.445504  0.070123  0.194227  0.051800
11   0.023986  0.972116  0.865167  0.890264  0.661421  0.700189
14   0.020202  0.136874  0.865757  0.901763  0.109192  0.510461
18   0.271728  0.534494  0.915533  0.980523  0.645168  0.327308
19   0.093618  0.526254  0.575011  0.185021  0.271042  0.597092
20   0.213655  0.903515  0.617589  0.722933  0.217435  0.959249
26   0.118694  0.710015  0.864928  0.459014  0.474889  0.783706
28   0.265763  0.084576  0.900053  0.248485  0.546677  0.090411
29   0.203953  0.018478  0.287226  0.237717  0.912467  0.143114
35   0.165518  0.403949  0.626008  0.081331  0.668583  0.571883
39   0.064386  0.546898  0.644630  0.693497  0.069129  0.831369
50   0.145404  0.602096  0.567876  0.599346  0.009390  0.073791
52   0.033285  0.236986  0.769306  0.195099  0.835728  0.063940
54   0.200802  0.898310  0.744139  0.974489  0.125608  0.473972
58   0.121146  0.123210  0.267667  0.373429  0.271528  0.691081
66   0.298609  0.821686  0.751373  0.594523  0.046632  0.972765
69   0.253856  0.968518  0.768065  0.280332  0.419290  0.119653
74   0.170942  0.661783  0.951298  0.295655  0.079433  0.177387
75   0.297852  0.973431  0.727517  0.888738  0.628704  0.368767
81   0.180711  0.555214  0.819045  0.330065  0.615941  0.689625
82   0.229102  0.846585  0.565516  0.962611  0.565496  0.968602
91   0.048279  0.586321  0.570630  0.387631  0.817507  0.188914
94   0.006307  0.358477  0.587666  0.279740  0.455779  0.415121
96   0.201203  0.544741  0.240799  0.728661  0.712201  0.234977
97   0.063182  0.765818  0.788724  0.156257  0.651651  0.057206
98   0.299849  0.725276  0.527310  0.842155  0.507292  0.597501
104  0.012332  0.199955  0.687854  0.530986  0.932580  0.437048
107  0.108589  0.393509  0.353052  0.284340  0.653202  0.883734
115  0.273306  0.848480  0.855806  0.901041  0.927299  0.423564
116  0.202949  0.781078  0.368215  0.440644  0.126920  0.704782
119  0.136435  0.566329  0.406082  0.165550  0.930542  0.488528
120  0.268281  0.354548  0.420842  0.374522  0.478156  0.491874
123  0.254074  0.108567  0.934646  0.524718  0.212609  0.478008
130  0.244139  0.402391  0.687608  0.075087  0.950675  0.079084
136  0.170245  0.110627  0.498974  0.631584  0.180117  0.077901
138  0.023543  0.205013  0.637902  0.418684  0.237191  0.574615
139  0.014442  0.648454  0.590568  0.258050  0.451720  0.641273
156  0.255389  0.968320  0.331191  0.091468  0.511206  0.667789
157  0.057478  0.723430  0.117211  0.259281  0.071527  0.897801
158  0.086938  0.142067  0.285407  0.489126  0.035500  0.657762
176  0.277436  0.949500  0.190197  0.963238  0.063024  0.434579
180  0.145108  0.834504  0.856365  0.925425  0.699716  0.705548
182  0.077916  0.750350  0.327145  0.565896  0.247442  0.529748
183  0.170100  0.599808  0.530476  0.273893  0.357626  0.668585
188  0.059241  0.736923  0.864269  0.412369  0.602914  0.830254
193  0.184425  0.373796  0.653367  0.345089  0.244703  0.336583
196  0.075375  0.791484  0.727688  0.066509  0.701156  0.844757
198  0.169031  0.423018  0.579953  0.936513  0.567897  0.507188
200  0.263419  0.940439  0.852790  0.266391  0.469353  0.714345
204  0.228080  0.522335  0.616137  0.451631  0.977010  0.781090
224  0.141356  0.176657  0.427900  0.642190  0.946484  0.128953
229  0.205906  0.115317  0.114105  0.756672  0.603998  0.794046
232  0.017549  0.076785  0.473000  0.904213  0.369013  0.933982
233  0.040568  0.849698  0.185114  0.990645  0.643789  0.412349
236  0.244822  0.768003  0.728435  0.376539  0.471014  0.052908
237  0.287347  0.083619  0.738780  0.456492  0.146348  0.522820
238  0.014565  0.552706  0.987821  0.413963  0.065781  0.841683
245  0.265855  0.527188  0.214017  0.861031  0.360308  0.656181
247  0.007139  0.864171  0.592912  0.450697  0.363164  0.985682
248  0.008315  0.801107  0.624795  0.420353  0.123617  0.630029

In [130]:
newdf.iloc[0,1]

np.float64(0.9734985125282465)

In [135]:
newdf.drop(["B"],axis = 1, inplace = True) # ,inplace = True    modifies the original

In [136]:
newdf.drop([1,5], axis =  0, inplace = True)

In [137]:
newdf.head(3)

              A         C         D         E         F
0  1.274575e+06  0.255598  0.240987  0.554703  0.713108
2  4.226702e-01  0.020417  0.961904  0.652673  0.951502
3  7.386427e-01  0.073017  0.687705  0.409687  0.003974

In [141]:
newdf.reset_index(drop = True, inplace = True)

In [142]:
newdf

                A         C         D         E         F
0    1.274575e+06  0.255598  0.240987  0.554703  0.713108
1    4.226702e-01  0.020417  0.961904  0.652673  0.951502
2    7.386427e-01  0.073017  0.687705  0.409687  0.003974
3    6.427633e-01  0.355112  0.092956  0.376108  0.236844
4    1.509429e-01  0.445504  0.070123  0.194227  0.051800
..            ...       ...       ...       ...       ...
243  2.658551e-01  0.214017  0.861031  0.360308  0.656181
244  7.189481e-01  0.757879  0.240438  0.853661  0.078308
245  7.138809e-03  0.592912  0.450697  0.363164  0.985682
246  8.315184e-03  0.624795  0.420353  0.123617  0.630029
247  5.946902e-01  0.771846  0.872772  0.832436  0.971130

[248 rows x 5 columns]

In [148]:
newdf['C'] = None # this is kinda wrong method to do instead use loc

In [151]:
newdf.loc[:,["C"]] = 56

In [152]:
newdf["C"]

0      56
1      56
2      56
3      56
4      56
       ..
243    56
244    56
245    56
246    56
247    56
Name: C, Length: 248, dtype: object

In [170]:
df = pd.DataFrame(
    {
        "name": ["Alfred", "Batman", "Catwoman"],
        "toy": [np.nan, np.nan, np.nan],
        "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT],
    })

In [159]:
df.head()

       name  toy       born
0    Alfred  NaN        NaT
1    Batman  NaN 1940-04-25
2  Catwoman  NaN        NaT

In [161]:
df.dropna(how = "all", axis = 1)

       name       born
0    Alfred        NaT
1    Batman 1940-04-25
2  Catwoman        NaT

In [162]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Alice", "David"],
    "Age": [25, 30, 25, 40],
    "City": ["NY", "LA", "NY", "Chicago"]
})

In [163]:
df

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago

In [165]:
df.drop_duplicates(keep = "last")

    Name  Age     City
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago

In [166]:
df.shape

(4, 3)

In [167]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   City    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [169]:
df["Name"].value_counts() #dropna = false/true

Name
Alice    2
Bob      1
David    1
Name: count, dtype: int64

In [171]:
df.notnull()

   name    toy   born
0  True  False  False
1  True  False   True
2  True  False  False

In [172]:
df.isnull()

    name   toy   born
0  False  True   True
1  False  True  False
2  False  True   True